### ISSUE TITLE
[ui] home_이벤트_추가_수정 / home뷰 다이얼로그 구현

### ISSUE THREAD

**Issue by murjune** [TeamHous/Hous-AosLab#4]
## 화면 이름
- home_이벤트_추가_수정

## 작업 내용 설명
- Home 다이얼로그 구현

## 필요 태스크
- [x] DatePickerDialog 구현
- [x] 하단 리사이클러뷰 구현

**Comment by papajj06** [comment]
구경하러 왔는데요 진짜 빠르네요
